### ISSUE TITLE
Raspbian Not Supported

### ISSUE THREAD

**Issue by rubeke4747** [Wolveix/Plexus#24] opened 2020-06-12 09:36 UTC
**Describe the bug**
When I type plexus list  -d "/mnt/media/Movies", the .txt file is not created
I also don't get any feedback in the CLI about whats happening.

**To Reproduce**
install on raspberry pi and test?

**Setup:**
 - OS: Raspbian

**Comment by Wolveix** [comment] 2020-06-12 10:40
This is a duplicate of the issue you opened yesterday (#23), please do not create duplicate issues in the future. Despite the fact that the other issue is now closed, you're still able to reply there.

Raspbian support was added yesterday when your previous issue was closed, I've tested this on my own Pi. Please try installing again using the automatic installer:

`curl https://plexus.wolveix.com/install.sh | sudo bash`

**Closed** 2020-06-15 14:23 UTC
Labels: duplicate
