### ISSUE TITLE
Unexpected token '&' at Line 654

### ISSUE THREAD

**Issue by parthp1808** [Wolveix/Plexus#32] opened 2021-01-16 01:06 UTC
![image](https://user-images.githubusercontent.com/13503697/104792609-ec735d00-576c-11eb-9602-bc16ba85e0e7.png)

I installed plexus in Macos Big sur and created list successfully too. When I ran the encode, it downloaded the file successfully and then broke at line 654 for syntax error.

**Comment by Wolveix** [comment] 2021-01-16 01:09
Hi! Thanks for taking the time to submit this issue. I'll look into this shortly. Would you mind supplying your config?

**Comment by parthp1808** [comment] 2021-01-16 01:12
> Hi! Thanks for taking the time to submit this issue. I'll look into this shortly. Would you mind supplying your config?

audio_codec="eac3"
blacklist_file="$HOME/.config/plexus/blacklist"
convert_dir="$HOME/.config/plexus/encode/convert"
converted_dir="$HOME/.config/plexus/encode/converted"
deinterlacing="true"
ffmpeg_binary="/usr/local/bin/ffmpeg"
ffmpeg_threads="2"
ffmpeg_preset="faster"
ffprobe_binary="/usr/local/bin/ffprobe"
force_overwrite="false"
fusermount_binary=""
hardware_acceleration="false"
hardware_codec="opencl"
list_file="$HOME/.config/plexus/list.txt"
media_container="mkv"
media_dir="/Users/parth/Documents/plex"
mount_dir="/Users/parth/Documents/plex"
rclone_binary="/usr/local/bin/rclone"
rsync_binary="/usr/bin/rsync"
video_codec="h265"
video_library="libx265"

**Comment by Wolveix** [comment] 2021-01-16 01:55
Thanks for providing that :) I'm unable to reproduce the issue with `zsh 5.7.1 (x86_64-debian-linux-gnu)`, but am able to reproduce it with `zsh 5.8 (x86_64-apple-darwin20.0)` which is probably what you're using (you can check via `zsh --version`). Continuing to look into this.

**Comment by Wolveix** [comment] 2021-01-16 02:29
Please run the following, and let me know if the issue persists:
```
curl -O https://raw.githubusercontent.com/Wolveix/Plexus/issue/32/plexus && mv plexus /usr/local/bin/plexus
```

**Comment by Wolveix** [comment] 2021-01-16 20:52
This issue seems to be resolved after some minor testing on my end, so I'm going to merge it into master and close this :) Please re-open it if the issue persists!

**Closed by Wolveix** 2021-01-16 20:52 UTC
